name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: docker build ${{ github.sha }}
        run: docker build -t adrichem/go-auth-proxy:${{ github.sha }} .

      - name: docker push ${{ github.sha }}
        run: docker push adrichem/go-auth-proxy:${{ github.sha }} 
      
      - name: docker tag latest
        run: docker tag adrichem/go-auth-proxy:${{ github.sha }} adrichem/go-auth-proxy:latest  
      
      - name: docker push latest
        run: docker push adrichem/go-auth-proxy:latest
